### ISSUE TITLE
i tried to generate. idk what's wrong

### ISSUE THREAD

**Issue by fountainpen** [satnaing/astro-paper#157] opened 2023-10-23 12:41 UTC
```
▶ src/pages/index.astro
  └─ /index.html (+73ms)
λ src/pages/rss.xml.ts
 error   [RSS] Invalid or missing options:
  Invalid input (items)
  File:
    src/pages/rss.xml.ts
  Stacktrace:
Error: [RSS] Invalid or missing options:
Invalid input (items)
    at validateRssOptions (file:///C:/Users/Parsifal/astro-paper-3.0.0/node_modules/.pnpm/@astrojs+rss@3.0.0/node_modules/@astrojs/rss/dist/index.js:46:26)
    at async getRssString (file:///C:/Users/Parsifal/astro-paper-3.0.0/node_modules/.pnpm/@astrojs+rss@3.0.0/node_modules/@astrojs/rss/dist/index.js:38:31)
    at async getRssResponse (file:///C:/Users/Parsifal/astro-paper-3.0.0/node_modules/.pnpm/@astrojs+rss@3.0.0/node_modules/@astrojs/rss/dist/index.js:30:21)
    at async callEndpoint (file:///C:/Users/Parsifal/astro-paper-3.0.0/node_modules/.pnpm/astro@3.1.3_@types+node@20.4.7/node_modules/astro/dist/core/endpoint/index.js:105:16)
    at async #tryRenderRoute (file:///C:/Users/Parsifal/astro-paper-3.0.0/node_modules/.pnpm/astro@3.1.3_@types+node@20.4.7/node_modules/astro/dist/core/pipeline.js:108:24)
    at async BuildPipeline.renderRoute (file:///C:/Users/Parsifal/astro-paper-3.0.0/node_modules/.pnpm/astro@3.1.3_@types+node@20.4.7/node_modules/astro/dist/core/pipeline.js:46:20)
    at async generatePath (file:///C:/Users/Parsifal/astro-paper-3.0.0/node_modules/.pnpm/astro@3.1.3_@types+node@20.4.7/node_modules/astro/dist/core/build/generate.js:410:16)
    at async generatePage (file:///C:/Users/Parsifal/astro-paper-3.0.0/node_modules/.pnpm/astro@3.1.3_@types+node@20.4.7/node_modules/astro/dist/core/build/generate.js:231:5)
    at async generatePages (file:///C:/Users/Parsifal/astro-paper-3.0.0/node_modules/.pnpm/astro@3.1.3_@types+node@20.4.7/node_modules/astro/dist/core/build/generate.js:144:9)
    at async staticBuild (file:///C:/Users/Parsifal/astro-paper-3.0.0/node_modules/.pnpm/astro@3.1.3_@types+node@20.4.7/node_modules/astro/dist/core/build/static-build.js:85:7)
```

**Comment by jbrr** [comment] 2023-11-01 21:04
is this the repo that threw that error? https://github.com/fountainpen/astro-paper

if so, I'm pretty sure you just named something wrong in your post schema. [`pubDate` is a required parameter](https://docs.astro.build/en/guides/rss/#generating-items), but it's named [`pubDatetime` in your repo](https://github.com/fountainpen/astro-paper/blob/main/src/content/config.ts#L9).

**Comment by fountainpen** [comment] 2023-11-02 05:47
isnt it the problem in rss????

**Comment by jbrr** [comment] 2023-11-02 06:00
yes, your content doesn't match the schema for an rss feed item, so it blows up when you try to create a feed. did you look in the [astro source code at the file and line number](https://github.com/withastro/astro/blob/main/packages/astro-rss/src/index.ts#L46) from the first line of the stack trace?

**Comment by jbrr** [comment] 2023-11-02 06:11
ohh, i'm sorry @fountainpen, I didn't realize that attribute was named wrong in this repo. i had assumed that was a custom schema you had put together for some reason 🤦‍♂️

**Comment by fountainpen** [comment] 2023-11-02 06:17
so basically there should be a ull request to fix that, huh?
if yes, pls make it.

**Comment by jbrr** [comment] 2023-11-02 06:40
it seems easy enough, but i can't replicate your issue. when you say you "tried to generate," do you mean you ran the `astro build` command?

**Comment by fountainpen** [comment] 2023-11-02 07:17
> it seems easy enough, but i can't replicate your issue. when you say you "tried to generate," do you mean you ran the `astro build` command?

that's right

**Comment by jbrr** [comment] 2023-11-02 15:02
I think I might be wrong. That parameter is actually changed to the proper `pubDate` before it's sent to the `@astro/rss` library: https://github.com/satnaing/astro-paper/blob/main/src/pages/rss.xml.ts#L18

Since I can't replicate the issue, and because I'm pretty busy at work right now, I don't think I'll have the time to dig into it any further, but I hope you figure it out!

**Comment by satnaing** [comment] 2024-07-16 15:28
Couldn't reproduce this issue.
I'll close this one for now. You can reopen or create new if you still have problems.

**Closed by satnaing** 2024-07-16 15:28 UTC
