### ISSUE TITLE
Switching theme and clicking "Go back" doesn't respect latest theme setting

### ISSUE THREAD

**Issue by rlopzc** [satnaing/astro-paper#110] opened 2023-08-29 08:36 UTC
To reproduce

1. Go to: https://astro-paper.pages.dev/
2. Click any post
3. Switch theme (top menu icon)
4. Click "Go back"
5. Theme is inverted
6. Refresh page and theme will be the toggled one

Gif:
![AstroPaper theme](https://github.com/satnaing/astro-paper/assets/6199588/1abf5e5c-ae36-47d1-bc5d-b5a83eb7fe61)

**Comment by ahmadkakarr** [comment] 2023-09-11 02:11
can not reproduce .. followed your steps... working fine for me

**Comment by tanishqmanuja** [comment] 2023-09-11 06:47
I have exactly the same issue, Can reproduce it pretty consistently.

**Comment by satnaing** [comment] 2023-09-15 04:25
Hello, does this bug still exist?
I cannot reproduce it right now.
I've migrated to Astro v3.1 and you can check it [here](https://astro-paper.pages.dev/).
If you still encounter this bug, please do let me know.

Also, can you provide more details about the bug. Like thses
- which OS/browser you're using
- maybe which version of browser you just tested
- etc....

**Comment by tanishqmanuja** [comment] 2023-09-15 04:57
Can confirm the bug is fixed in the version 3 branch but still present on the main branch.

**Comment by satnaing** [comment] 2023-12-09 02:50
I assume this issue is already fixed in v3. Thus, I'll close this for now.

**Closed by satnaing** 2023-12-09 02:50 UTC
